### ISSUE TITLE
NPM run dev issue

### ISSUE THREAD

**Issue by abdokouta** [ahalimkara/nuxt-apollo#1]
hello, thanks for this repo. it's awesome but i got an issue while running the repo. i got error that it says ("31:15-27 "export 'willPrefetch' was not found in 'vue-apollo'") i have googled it and i have figure out that apollo new update hasn't willPrefetch anymore and after removing willPrefetch from Nav.vue in Components folder i got new error that it says ("apolloProvider.prefetchAll is not a function") ... could u please help?

**Comment by antoniomarcosferreira** [comment]
Congratulations on the repository, I have the same problem (willPrefetch), but I really want to help with this project. **Can we update this?**

**Comment by ahalimkara** [comment]
@antoniomarcosferreira sure, any PRs are welcome!

**Comment by ahalimkara** [comment]
I have just upgraded all the packages, willPrefetch error shouldn't happen anymore.
