### ISSUE TITLE
Cannot install the packages using YARN

### ISSUE THREAD

**Issue by Himujjal** [ahalimkara/nuxt-apollo#2]
Trying to install the packages gives the following errors:

```
upath@1.0.2: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "11.6.0"
```

I can degrade my node version but I think this repo should keep up with all the node versions

### Config:
**node**: v11.6.0
**yarn**: v1.13.0
**vue-cli**: v3.3.0
**nuxt-cli**: v2.3.4
**OS**: Windows 10

Steps to recreate the issue:
```
git clone https://github.com/ahalimkara/nuxt-apollo
cd nuxt-apollo
yarn install
```

**Comment by ahalimkara** [comment]
I have rewrote the project and now you should be able to install with yarn, sorry for the delayed reply.

**Comment by Himujjal** [comment]
Lol. I have gone beyond Vue & front-end dev in general now. Thank you anyways.
